- name: universal docker setup
  hosts: all
  become: yes
  tasks:
    - name: install general dependencies
      package:
        name: [curl, ca-certificates, gnupg]
        state: present

    - name: create keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: add docker gpg key
      shell: |
        curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: setup docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: install docker engine
      package:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
        state: present
