name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: deps
        run: pip install -r ml/requirements.txt

      - name: run
        run: python ml/main.py
